language: emacs-lisp
sudo: required
matrix:
  fast_finish: true
env:
  global:
    - PATH=$HOME/.evm/bin:$HOME/.cask/bin:$PATH
  matrix:
    - EVM_EMACS=emacs-24.3-travis
    - EVM_EMACS=emacs-24.4-travis
    - EVM_EMACS=emacs-24.5-travis
    - EVM_EMACS=emacs-git-snapshot
before_install:
  - git clone https://github.com/rejeep/evm $HOME/.evm
  - git clone https://github.com/cask/cask $HOME/.cask
  - evm config path /tmp
install:
  - ./script/install_tramp.sh
  - if [ $EVM_EMACS = emacs-git-snapshot ];
    then
        ./script/install_emacs_build_deps.sh;
    fi
  - evm install $EVM_EMACS --use
  - cask install
script:
  - cask exec ert-runner -l test/interpreters/$INTERPRETER.el
