- name: install evm
  git: repo=https://github.com/rejeep/evm dest=~/.evm
- name: create evm directory
  file: dest=/usr/local/evm state=directory mode=0777
- name: install emacs
  command: evm install {{ item }}
  with_items:
    - emacs-24.3-bin
    - emacs-24.4-bin
    - emacs-24.5-bin
